const { createClient } = require('@supabase/supabase-js');

const url = 'https://kyrargxececkgbrlzvqs.supabase.co';
const key = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5cmFyZ3hlY2Vja2dicmx6dnFzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc5MDk1ODYxMCwiZXhwIjoyMTA2NTM0NjEwfQ.aApRX5bvQ4D012_nNYkESmkA60Z6j1QibJGmuvwWNcM';
const supabase = createClient(url, key);

const products = [
  {
    id: 'prod-001',
    slug: 'minimalist-leather-cardholder',
    name: 'Minimalist Leather Cardholder',
    description: 'Slim Italian vegetable-tanned leather wallet with four card slots and a center cash compartment. Hand-burnished edges that develop a rich patina over time.',
    price_kobo: 1850000,
    currency: 'NGN',
    category: 'carry',
    image_url: '/images/products/cardholder.svg',
    stock: 24,
    featured: true,
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'prod-002',
    slug: 'brass-key-organizer',
    name: 'Solid Brass Key Organizer',
    description: 'Precision CNC-machined brass bar with stainless steel washers. Holds up to 6 keys securely without jingling or scratching your phone screen.',
    price_kobo: 1200000,
    currency: 'NGN',
    category: 'carry',
    image_url: '/images/products/key-organizer.svg',
    stock: 18,
    featured: false,
    created_at: '2026-09-02T08:00:00Z',
  },
  {
    id: 'prod-003',
    slug: 'titanium-pocket-pry-bar',
    name: 'Titanium Pocket EDC Tool',
    description: 'Grade 5 titanium multi-function pocket pry bar featuring an integrated bottle opener, standard bit driver, and deep-carry pocket clip.',
    price_kobo: 2200000,
    currency: 'NGN',
    category: 'carry',
    image_url: '/images/products/pry-bar.svg',
    stock: 12,
    featured: true,
    created_at: '2026-09-03T08:00:00Z',
  },
  {
    id: 'prod-004',
    slug: 'waxed-canvas-carryall',
    name: 'Waxed Canvas Utility Carryall',
    description: 'Rugged 16oz water-repellent waxed canvas tote with full-grain bridle leather handles and brass rivet reinforcements. Built to endure daily commutes.',
    price_kobo: 4500000,
    currency: 'NGN',
    category: 'carry',
    image_url: '/images/products/carryall.svg',
    stock: 9,
    featured: true,
    created_at: '2026-09-04T08:00:00Z',
  },
  {
    id: 'prod-005',
    slug: 'solid-brass-mechanical-pencil',
    name: 'Solid Brass Mechanical Pencil',
    description: '0.5mm drafting pencil crafted with a hexagonal brass barrel and diamond knurled grip. Perfectly balanced for long writing and sketching sessions.',
    price_kobo: 1450000,
    currency: 'NGN',
    category: 'stationery',
    image_url: '/images/products/pencil.svg',
    stock: 30,
    featured: true,
    created_at: '2026-09-05T08:00:00Z',
  },
  {
    id: 'prod-006',
    slug: 'minimalist-grid-notebook',
    name: 'Hardcover Grid Journal (192 Pages)',
    description: 'Thread-bound lay-flat notebook featuring 100gsm fountain-pen friendly acid-free paper, subtle 5mm light gray dot-grid, and ribbon marker.',
    price_kobo: 950000,
    currency: 'NGN',
    category: 'stationery',
    image_url: '/images/products/notebook.svg',
    stock: 45,
    featured: false,
    created_at: '2026-09-06T08:00:00Z',
  },
  {
    id: 'prod-007',
    slug: 'stoneware-desk-pen-stand',
    name: 'Ceramic Minimalist Pen Stand',
    description: 'Wheel-thrown stoneware pen stand with a raw basalt matte finish. Weighted base with cork bottom to protect your desk surface.',
    price_kobo: 800000,
    currency: 'NGN',
    category: 'stationery',
    image_url: '/images/products/pen-stand.svg',
    stock: 15,
    featured: false,
    created_at: '2026-09-07T08:00:00Z',
  },
  {
    id: 'prod-008',
    slug: 'aluminum-pocket-fountain-pen',
    name: 'Anodized Aluminum Fountain Pen',
    description: 'Compact pocket-sized fountain pen machined from aircraft-grade aluminum. Includes a German stainless steel fine nib and brass converter.',
    price_kobo: 2800000,
    currency: 'NGN',
    category: 'stationery',
    image_url: '/images/products/fountain-pen.svg',
    stock: 16,
    featured: true,
    created_at: '2026-09-08T08:00:00Z',
  },
  {
    id: 'prod-009',
    slug: 'dual-sided-desk-mat',
    name: 'Dual-Sided Felt & Vegan Leather Desk Pad',
    description: 'Large 900x400mm desk mat offering high-density Merino wool felt on one side and smooth water-resistant vegan leather on the other.',
    price_kobo: 3200000,
    currency: 'NGN',
    category: 'desk',
    image_url: '/images/products/desk-mat.svg',
    stock: 20,
    featured: true,
    created_at: '2026-09-09T08:00:00Z',
  },
  {
    id: 'prod-010',
    slug: 'solid-walnut-phone-dock',
    name: 'Solid Walnut Phone Dock',
    description: 'Carved from a single piece of kiln-dried American walnut with precision angled viewing slot and hidden cable routing channel underneath.',
    price_kobo: 1650000,
    currency: 'NGN',
    category: 'desk',
    image_url: '/images/products/phone-dock.svg',
    stock: 14,
    featured: false,
    created_at: '2026-09-10T08:00:00Z',
  },
  {
    id: 'prod-011',
    slug: 'magnetic-desktop-cable-organizer',
    name: 'Weighted Magnetic Cable Block',
    description: 'Solid zinc and silicone weighted desktop block with three magnetic cable collars that keep charging cables right where you need them.',
    price_kobo: 1100000,
    currency: 'NGN',
    category: 'desk',
    image_url: '/images/products/cable-block.svg',
    stock: 22,
    featured: false,
    created_at: '2026-09-11T08:00:00Z',
  },
  {
    id: 'prod-012',
    slug: 'matte-stoneware-coffee-mug',
    name: 'Matte Stoneware Coffee Mug',
    description: 'Handcrafted 360ml ceramic mug with ergonomic geometric handle and a tactile charcoal glaze. Microwave and dishwasher safe.',
    price_kobo: 950000,
    currency: 'NGN',
    category: 'desk',
    image_url: '/images/products/ceramic-mug.svg',
    stock: 35,
    featured: true,
    created_at: '2026-09-12T08:00:00Z',
  },
  {
    id: 'prod-013',
    slug: 'cedar-amber-soy-candle',
    name: 'Cedar & Amber Soy Wax Candle',
    description: 'Slow-burning 280g natural soy wax candle poured into a matte black vessel with an organic crackling wood wick. 55-hour clean burn time.',
    price_kobo: 1350000,
    currency: 'NGN',
    category: 'living',
    image_url: '/images/products/candle.svg',
    stock: 28,
    featured: true,
    created_at: '2026-09-13T08:00:00Z',
  },
  {
    id: 'prod-014',
    slug: 'botanical-room-linen-mist',
    name: 'Sandalwood Botanical Room Mist',
    description: '100ml relaxing blend of pure sandalwood, vetiver, and bergamot essential oils in an ultraviolet apothecary glass bottle with fine atomizer.',
    price_kobo: 1050000,
    currency: 'NGN',
    category: 'living',
    image_url: '/images/products/room-mist.svg',
    stock: 19,
    featured: false,
    created_at: '2026-09-14T08:00:00Z',
  }
];

async function seed() {
  const { data, error } = await supabase.from('products').upsert(products, { onConflict: 'id' }).select();
  if (error) {
    console.error('Seed error:', error);
    process.exit(1);
  } else {
    console.log('Successfully seeded ' + data.length + ' products into Supabase database!');
  }
}

seed();
